### ISSUE TITLE
Decide on project goal

### ISSUE THREAD

**Issue by TheEimer** [LUH-AI/robotics-project-24#1]

**Comment by ThorKlm** [comment]
Project goals decided: Two subprojects, the first focusing on a physical plant watering setup to be used by a simmulation trained Reinforcement Learning agent in order to efficiently find and water plants in the room. The second being a ball kicking and ball handling task. Given their overlapping development needs, only a portion of team members will be fully dedicated to one subproject, with most focusing on shared tasks.
